### ISSUE TITLE
ToDo Before Release

### ISSUE THREAD

**Issue by krischer** [krischer/instaseis#1]
- [x]  5 - 10 MB datbenbank für tests, all modes (fwd, bwd, displ_only,
fullfields)

- [x] rename

- [x] test coverage

- [x]  fullfields modus

- [x]  lanczos resampling in obspy

- [x]  documentation, examples

- [x]  parallel IO

- [x]  lokaler webservice

- [x]  refactoring

- [x] installation with setup.py

- [x] travis integration

- [x] PEP8 checks in tests

- [x] Rebase history to exclude large binary files

- [x] Test if only one file is present

- [x] Test without read-on-deman

- [x] Test for fullfield mode and test data

- [x] tests for strain only mode

- [x] force source tests

- [x] Finite with source time function test + srf reader

- [x] CMTSOLUTION reader, source from strike dip rake

- [x] Test _get_band_code()

- [x] Doctest for DB testing

- [x] Resampling test

- [x] Buffer test

- [x] Raise warning if depth of source/receiver is set in different modes

- [x] Format support for sources (QuakeML, NDK (once obspy has a new release))

- [x] either make the sem_derivative tests work or scrap them
